Fixes for Julia nightly
EcoJulia/EcoSISTEM.jl pull request #73
Opened 2021-07-28 08:36 UTC by claireh93

JLD is outdated, so dropping support for it and using JLD2 instead - Closes #71

2021-08-02 10:26 UTC, claireh93 commented
@richardreeve This should be sorted now - have tested it on the nightly release! Support for JuliaDB has been removed for now, pending their release of a new version.

2021-08-10 10:18 UTC, richardreeve requested changes
I think delete all of the ClimatePref files and then it'll be good to go.

2021-08-10 10:18 UTC, richardreeve commented on src/ClimatePref/ClimatePref.jl
> +@warn "This functionality remains under development!"
I think just delete all of these ClimatePref files...

2021-08-13 13:55 UTC, richardreeve approved these changes

2021-08-13 13:57 UTC, merged